 development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: task_app_development
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: task_app_test
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  
production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: task_app_production
  pool: 5
  username: postgres
  password: 123456
  host: localhost